### ISSUE TITLE
media-progress-dired-mode not work with other dired-mode-hook functions

### ISSUE THREAD

**Issue by stardiviner** [jumper047/media-progress#1]
my original Dired buffer showing files list like this:

<img width="743" alt="image" src="https://github.com/jumper047/media-progress/assets/378699/35aabf85-db0d-4b50-ab9c-ec7e1cee5456">

my config:

```elisp
(use-package media-progress
  :ensure t
  :ensure media-progress-dired
  :hook (dired-mode . media-progress-dired-mode)
  ;; :config (add-hook 'dired-mode-hook #'media-progress-dired-mode 100) ; I also tried to put hook function at end. not work.
  )
```

After enabled `media-progress-dired-mode`, it becomes this:

<img width="381" alt="image" src="https://github.com/jumper047/media-progress/assets/378699/e20da2b6-a583-4f15-9b9c-f8195e8d12d0">

Then I manually disable `media-progress-dired-mode`, it becomes:

<img width="548" alt="image" src="https://github.com/jumper047/media-progress/assets/378699/b106d289-c143-4adf-abd2-b3b39df1b23a">

Then I manually enable `media-progress-dired-mode` again, it's correct now:

<img width="642" alt="image" src="https://github.com/jumper047/media-progress/assets/378699/733d3cc2-825a-43ad-b9fb-e2765cb6bc7c">

**Comment by jumper047** [comment]
Hmm, interesting - seems like this is intended behavior (most of the dired related code was borrowed from `dired-git-log` package), but actually it have no sense for this plugin, because string is rather small. For now you can set variable `media-progress-dired-auto-hide-details-p` to nil - it should help

**Comment by stardiviner** [comment]
Indeed, this option workd as I want. Thanks, @jumper047
