### ISSUE TITLE
mpv config

### ISSUE THREAD

**Issue by Ypot** [jumper047/media-progress#2]
Hi
Thanks for this package.
I am trying to use it, but I can't find where to modify the "mpv config" file.

I am using mpv in Windows.

Best regards

**Comment by jumper047** [comment]
Hi, seems like on windows MPV config should be located in `%appdata%\mpv\` directory. I'm on vacation right now and don't have windows PC by hands, so can't check it by myself though. Please let me know if it helps (if not - I'll try to find PC somewhere and check it out by myself)

**Comment by jumper047** [comment]
Update: I'm unwillingly misinformed you - it's `%appdata%\Roaming\mpv`. Now I mentioned correct location in README, and also set up `media-progress-mpv-cfg-dir` variable to correct one depending on your OS (Linux/Windows for now). I'm closing issue, feel free to reopen it if something is not working for you!
